### ISSUE TITLE
Queue for img2img upscale chain

### ISSUE THREAD

**Issue by Stibo** [Kryptortio/SDAtom-WebUi-us#10]
Great extension! I actually don't know if the extension already allows this, but is it possible to create a queue for SD Upscale and every step in the queue takes the previously generated image to upscale it even further? For every step different settings but every step takes the previously generated image? I hope you get what I mean.

**Comment by Stibo** [comment]
Thanks for the quick reply, that looks promising. I will try that out.

Another question related to this topic:

Is it possible (with another extension function) to process a different image (that was previously generasted in txt2img without this extension) with each step?

I plan to generate some images with txt2img (manually) and upscale them up to 8k. The first few steps are relatively fast, but as soon as I get from 4k to 8k (with the sd upscale 2x) then it will take 1-2h. My plan is to manually upscale a few pictures up to 4k and then create a queue to generate 5-6 8k images over night. So if I wake up I have 5-6 of the manually generated small txt2img images in 8k as soon as I wake up. With that feature I could do this passively without any interaction and it does not block my GPU the whole day.

Maybe you have an idea how this can be done?

**Comment by Kryptortio** [comment]
Maybe just try using the i2i batch tab? If you need different settings for each I think you could put each image in a separate folder and create one queue entry for each folder (have not used the batch feature myself).

**Comment by Stibo** [comment]
Oh I forgot about that feature. Thanks, I'll try that out!

Keep up the great work! Cheers
