### ISSUE TITLE
Bug with img2img batch

### ISSUE THREAD

**Issue by Stibo** [Kryptortio/SDAtom-WebUi-us#11]
While trying to optimize my sd upscale process I encountered a bug in the queue system. I tried to add a few img2img batch jobs to the queue. It looks like the output directory is not added to the queue json field. I assume it should be the "i2iBatchOutputDir" property? This property is empty every time. So I added the output path manually to the json. If I do so, the "Inpaint batch mask directory" field is filled with the path from "i2iBatchOutputDir" but the output directory field stays the same value I've entered last.

So it looks like one property is missing (there should be 3 different paths in the json (input directory,  output directory and inpaint batch mask directory).

Just to reproduce this issue, heres what I tried:
- Created a folder "in" and put a 512x512 txt2img image in the folder
- Create an empty folder "out"
- Create an empty folder "out2"
- Added a img2img batch to the queue with "in" as input directory and "out" as output directory... All the other settings are not important in this case (I just did a SD upscale 1.1x)
- Add another img2img batch to the queue with "out" as input directory and "out2" as output directory. For the other settings, same as above.
- Press process queue
- Watch closely what happenes to the 3 path fields from the batch tab

I hope you can help me with this bug/issue? That would speed up my workflow extremely, if that would work as expected.

**Comment by Kryptortio** [comment]
Thanks, pushed a new version that should fix this issue.
