### ISSUE TITLE
Unexpected behavior when prompt in queue refers to an unavailable model

### ISSUE THREAD

**Issue by Trevor-Z** [Kryptortio/SDAtom-WebUi-us#15]
When I queue a prompt, it includes the current model in its settings. And when I process the queue, the prompt selects that model, if it's available. But if it isn't available, it picks another random model, instead of using the one currently selected.

What's the expected behavior for the extension when it processes a prompt that refers to a model that's not available anymore? And is it possible to add a setting to use the current selection, whether the one in the prompt is available or not?

**Comment by Kryptortio** [comment]
I pushed [a new commit](https://github.com/Kryptortio/SDAtom-WebUi-us/commit/b3dacef5695a01bbd0050872574b69128098daf8) that should fix this.
