### ISSUE TITLE
Overwrite settings doesn't work from Image Browser tab (A1, A2, A3)

### ISSUE THREAD

**Issue by jricketson** [Kryptortio/SDAtom-WebUi-us#17]
The overwrite settings only work if they are overwriting a property that is already set. In the ImageBrowser case, I am trying to add new settings in most cases (eg HiRes this image, or 5 new versions of this image).
`
                 if(p_overwrite_data) {
			awqLog('appendQueueItem: Adding to queue with Overwrite button');
			let jsonData = JSON.parse(itemJSON.value);
			for(let setKey in jsonData) {
				if(p_overwrite_data.hasOwnProperty(setKey)) jsonData[setKey] = p_overwrite_data[setKey];
			}
			itemJSON.value = JSON.stringify(jsonData);
		}
`

**Comment by Kryptortio** [comment]
Right, I changed it, you can now try to overwrite with any property.
