### ISSUE TITLE
Bug with Extras tab upscaling queue

### ISSUE THREAD

**Issue by Stibo** [Kryptortio/SDAtom-WebUi-us#23]
I found a bug while using the extras to upscale an image.

Looks like jobs from the Extras tab are looped endlessly and are never completed. I simply added a job with a 512x512 image, "scale by: resize 2x" and any upscaler, added it to the queue and started it.  Then I added another job with another upscaler (to compare afterwards) and it just looped the first  job endlessly, never changing from "1" to "0" and never doing the second job in the queue. 

Is this really a bug or just some user error from my side?

**Comment by Kryptortio** [comment]
I suspect the reason for this is that the script has an issue when things happen to fast, so the task completes before the script registers that is has started. A new way to track when tasks starts or stops might be needed to solve this.

**Comment by Kryptortio** [comment]
I checked to confirm this and there was actually an issue with the current check as well. I have pushed a new version that should help with this. The issue above could still occur but now it hopefully works most of the time.

**Comment by Kryptortio** [comment]
Since there was no response I'll hope the fix was enough to solve this issue.

**Comment by Stibo** [comment]
Sorry, I forgot to answer. Thanks for the fix, looks like it works way more reliable now!
