### ISSUE TITLE
Extension is not working on a fresh install of A1111

### ISSUE THREAD

**Issue by Trevor-Z** [Kryptortio/SDAtom-WebUi-us#24]
Just reinstalled A1111 doing a git pull of the repo, and immediately installed the extension.

Nothing shows up, neither the button at the top or the UI at the bottom.

**Comment by Kryptortio** [comment]
I suggest that when you run into an issue, check this first https://github.com/Kryptortio/SDAtom-WebUi-us#troubleshooting

**Comment by Trevor-Z** [comment]
It worked, thanks.

Does the extension save data externally? It reloaded the queue I had before deleting the WebUI folder and reinstalling.

**Comment by Kryptortio** [comment]
Yes and no, the data is saved in your web browser using [local storage](https://en.wikipedia.org/wiki/Web_storage).
