### ISSUE TITLE
Extension stopped working after trying to import queue data

### ISSUE THREAD

**Issue by Trevor-Z** [Kryptortio/SDAtom-WebUi-us#27]
I wanted to test what happened to the existing queue when you imported more data, so I copied and pasted the first item on the queue list, and when I hit import, the extension disappeared.

Nothing worked to bring it back, restarting the UI, restarting the server, deleting the extension folder and reinstalling.

**Comment by Kryptortio** [comment]
First step when nothing is working is to check the [Troubleshooting section](https://github.com/Kryptortio/SDAtom-WebUi-us#troubleshooting). If you pasted something incorrectly in import you might need the last part (reset).

**Comment by Trevor-Z** [comment]
Right, I should have done that.

The reset worked, but I can reproduce the issue. Create any prompt, send it to the queue, then copy the item and paste to import it, close the settings window, open it to paste and import again, and the extension is gone.

This is what I copied and pasted:

{"type":"t2i","prompt":"masterpiece, best quality, aerial view of manhattan","negPrompt":"worst quality","sample":"20","sampleMethod":"Euler a","width":"512","height":"512","restoreFace":false,"tiling":false,"highresFix":false,"hrFixUpscaler":"Latent","hrFixSteps":"0","hrFixdenoise":"0.7","hrFixUpscaleBy":"2","hrFixWidth":"0","hrFixHeight":"0","batchCount":"1","batchSize":"1","cfg":"7","seed":"1032830259","extra":false,"varSeed":"-1","varStr":"0","varRSFWidth":"0","varRSFHeight":"0","script":"None","scriptPromptMatrixPutVar":false,"scriptPromptMatrixUseDiff":false,"scriptXYZXtype":"Seed","scriptXYZXVals":"","scriptXYZYtype":"Nothing","scriptXYZYVals":"","scriptXYZZtype":"Nothing","scriptXYZZVals":"","scriptXYZDrawLeg":true,"scriptXYZIncludeSubImg":false,"scriptXYZIncludeSubGrid":false,"scriptXYZKeepMOne":false,"scriptXYZGridMargin":"0","sdModelCheckpoint":"- Photo\\juggernaut_v18.safetensors [3f0f3a35e2]"}

**Comment by Kryptortio** [comment]
That's not how the import feature under script settings works, you are not supposed to import queue items there but all the script data. First click the button when the text-box is empty to export then that is what you can later import again (this includes the entire queue and all script settings).

If you want to import a single queue item, just click add and replace whatever you just added in the queue directly.
