### ISSUE TITLE
Set up multiple runs of the queue with different models

### ISSUE THREAD

**Issue by Trevor-Z** [Kryptortio/SDAtom-WebUi-us#28]
Suppose I have 20 items lined up, and would like to run the queue 5 times, but each with a different model. Is there a way to automate this, other than creating manually all the resulting 100 items in the queue? If not, would it be possible to implement this functionality?

**Comment by Kryptortio** [comment]
The easiest way would probably be to export the data, then in notepad you use replace to change for example 
> "sdModelCheckpoint":"endlessreality_v11.safetensors [1dd56f8b12]" 

to
> "sdModelCheckpoint":"dreamlike-photoreal-2.0x768.safetensors [92970aa785]"

And then reimport. Another way to do it it to click load on one item then go to settings and add the other model in one of the alt X buttons. E.g under "Alt 1 overwrite" put `{"sdModelCheckpoint":"dreamlike-photoreal-2.0x768.safetensors [92970aa785]"}` then after loading one item re-add it with the A1 button.

**Comment by Trevor-Z** [comment]
I see. But still, it'd be necessary to rebuild the queue for every run with a new batch of models, even item by item in the second case.

The first option would mostly work if importing added to the queue, instead of replacing it entirely. I could keep a txt with the 20 prompts, replace the model there and import 5 times to build the queue step by step, even allowing for mistakes along the way, instead of having to plan it beforehand to import all at once, like it is now.

**Comment by Kryptortio** [comment]
If you want to run the same queue again and only change the model then exporting everything under settings and replacing the model and then reimporting should work in one go.

Using the alt button is the better option if you know from the start what models you want to try with since then you could just click several buttons at once. However you could also just go through the queue clicking load > A1, load > A1 and so on until you have added everything again with a different model.

**Comment by Trevor-Z** [comment]
Got it, thanks.

Also, if it's technically feasible, some kind of integration with the x/y/z plot script would be an awesome festure.

**Comment by Kryptortio** [comment]
> A way to do incremental imports, adding one or more items to the existing queue, for cases like this, where one might keep several items on a txt and edit them there.

For adding a single item you can just click add then replace the content of that row manually.
For entire queue's you could manually replace the queue in a full export, if you put your export in this page it will be easeer to read it https://jsonformatter.org/

Then you could just change the content of the queue before importing it to whatever queue you want:

```
...
  "currentQueue": [
    <queue entry>,
    <queue entry>,
    <queue entry>,
],
...
```

> integration with the x/y/z plot

This is already supported as far as I know.

**Comment by Trevor-Z** [comment]
> > integration with the x/y/z plot
> 
> This is already supported as far as I know.

Is it? What I had in mind was running a plot with the queue as X type, and the different models as Y type.

**Comment by Kryptortio** [comment]
> What I had in mind was running a plot with the queue as X type, and the different models as Y type.

The script x/y/z plot is supported, this is something entirely different. Also I think it it a very niche feature that could be mostly covered by just using the AX buttons and clicking 1-3 of them when adding to queue, then you would already be at 4 different models.

**Comment by Kryptortio** [comment]
There is now a feature under script settings that lets you replace the model for all entries in your queue at once (or something else in another attribute).
