### ISSUE TITLE
[BUG] Pixel ratio keeps rounding + color issues

### ISSUE THREAD

**Issue by oga-sven** [Kryptortio/SDAtom-WebUi-us#29]
I am using the extention (https://github.com/Kryptortio/SDAtom-WebUi-client-queue-ext)

When i add something to the queue, the pixel ratio keeps shifting. i currently do renders at 960 X 540 (half of full HD). When they get added to the queue it gets saved as 544 (the 960 is not touched). When the queue gets processed it also applies as 544 so it is not a visual bug. 

Also. the colors seem off at some places
This screenshot might look weird, but this is my top right corner to add things to the queue. the process queue text at the bottom is also not readable
![image](https://github.com/Kryptortio/SDAtom-WebUi-us/assets/31472764/9e60efd8-db6b-49e7-b613-41465193f0fe)

**Comment by Kryptortio** [comment]
This is unrelated to the extension/script, AUTOMATIC1111 has a fixed multiple you have to follow. It's 8 meaning 544 (8*68) is allowed but not 540. When you enter 540 and hold the mouse over it you are told that it's an invalid value.

You can change the opacity (Button transparency) of the buttons under script settings if you want to see it more clearly.

**Comment by oga-sven** [comment]
Dont know how, but after uninstalling a specific unrelated extention, it seemed to work now
