### ISSUE TITLE
prompt isnt saved in the queue

### ISSUE THREAD

**Issue by degesz** [Kryptortio/SDAtom-WebUi-us#3]
Hello, i have an issue that the prompt isnt saved in the queue, it only saves info about the checkpoint

example:  {"sdModelCheckpoint":"f222.ckpt [44bf0551]"}

It worked fine yesterday, I'm not aware of updating anything, no clue whats wrong.

i really liked this thing, would be nice if someone helped me get it working again

**Comment by Kryptortio** [comment]
One reason this would be happening is that you are on an unsupported tab when clicking add to queue. The script only works for txt2img, img2img and Extras. If you have the latest version of the script (and the web-ui), there is now a "verbose" option for script outputs that might log an error if there is another issue.

**Comment by degesz** [comment]
I'm using it on txt2img so that isnt problem

now it doesnt save anything not even the model

screencap:  https://youtu.be/EFBkeFigUZU

**Comment by degesz** [comment]
ok updating webui solved it thanks
