### ISSUE TITLE
Errors in console if `Hidden UI tabs` (`hidden_tabs`) enabled

### ISSUE THREAD

**Issue by LEv145** [Kryptortio/SDAtom-WebUi-us#32]
![изображение](https://github.com/Kryptortio/SDAtom-WebUi-us/assets/40071054/19539192-10b3-4e14-ad04-890c7bc5df10)
![изображение](https://github.com/Kryptortio/SDAtom-WebUi-us/assets/40071054/ee733bcf-068c-4912-af3e-ca6f352eb94a)

Queue buttons also stop working

**Comment by Kryptortio** [comment]
Yes, if you remove tabs that it relies on it will cause issues, however it should work hiding it with [script extensions](https://github.com/Kryptortio/SDAtom-WebUi-us#script-extensions) instead if you want, like this:

`document.querySelector(conf.ext.controls.tabButton.sel).style.display = 'none' ;`

**Comment by LEv145** [comment]
I don't have queue buttons displayed, but when I disable `hidden_tabs', then everything works
![изображение](https://github.com/Kryptortio/SDAtom-WebUi-us/assets/40071054/fd30c9b3-4a2a-4d40-8d8a-f993cae5fa09)
Script extensions is empty
![изображение](https://github.com/Kryptortio/SDAtom-WebUi-us/assets/40071054/4e51b2b8-a4d7-4969-b066-9b203a37158d)

**Comment by Kryptortio** [comment]
Try not hiding the extra tab and paste the script I added [above](https://github.com/Kryptortio/SDAtom-WebUi-us/issues/32#issuecomment-1606099993) as an [extension script](https://github.com/Kryptortio/SDAtom-WebUi-us#script-extensions) instead.

**Comment by LEv145** [comment]
> Try not hiding the extra tab and paste the script I added [above](https://github.com/Kryptortio/SDAtom-WebUi-us/issues/32#issuecomment-1606099993) as an [extension script](https://github.com/Kryptortio/SDAtom-WebUi-us#script-extensions) instead.

This seems to hide `Extras', but these tabs should be hidden via auto1111, not the extension

**Comment by Kryptortio** [comment]
That would probably require a big rework for something I think not many care about. The workaround above should work though, you can hide the other tabs with settings instead if you want.

Or you can try this https://github.com/ArtVentureX/sd-webui-agent-scheduler

**Comment by LEv145** [comment]
> That would probably require a big rework for something I think not many care about. The workaround above should work though, you can hide the other tabs with settings instead if you want.
> 
> Or you can try this https://github.com/ArtVentureX/sd-webui-agent-scheduler

Thanks for the workaround!

I hope that you will find an easy way to fix it without rewriting. In early versions, the buttons were displayed, although the console wrote errors

**Comment by LEv145** [comment]
I think need to somehow force the extension to display the buttons, then everything will work
