### ISSUE TITLE
Look for inputs by id attributes for json parameters not matching template

### ISSUE THREAD

**Issue by skittlz444** [Kryptortio/SDAtom-WebUi-us#33]
Hi, for items not matching the available input list, can it be implemented to search the dom for an element matching the parameter's id and fill that? For instance, things like seed, etc work fine, but if I want to set up controlnet settings in the queue, I should be able to add the following to the queue item's json:
```
    "img2img_controlnet_ControlNet-0_controlnet_enable_checkbox":true,
    "img2img_controlnet_ControlNet-0_controlnet_pixel_perfect_checkbox":true,
    "img2img_controlnet_ControlNet-0_controlnet_type_filter_radio":"Tile",
    "img2img_controlnet_ControlNet-0_controlnet_preprocessor_dropdown":"tile_resample",
    "img2img_controlnet_ControlNet-0_controlnet_model_dropdown":"control_v11f1e_sd15_tile [a371b31b]"
```
Each key here matches the id of the DOM element in the controlnet extension, and theoretically the keys are also correct (a little hard to test though without this implemented).
Implementing this would allow for _almost_ unlimited queueing functionality, with only extensions that don't implement id's properly not working (looking at you Ultimate SD Upscale).

**Comment by Kryptortio** [comment]
Nice, looks like they have added some useful id's now. 

It's possible to add additional elements like this using ["script extensions"](https://github.com/Kryptortio/SDAtom-WebUi-us#script-extensions)
```
conf.t2i.cnEnable = {sel:"#txt2img_controlnet_ControlNet-0_controlnet_enable_checkbox input"};
conf.t2i.newElem = {grad:"element_id"}; // Add an element directly through gradio data structure with id element_id 
conf.i2i.newElem2 = {grad:"element_id"}; // Same as above but for i2i
conf.ext.newElem3 = {grad:"element_id"}; // Same as above but for extra tab
```
This will not work for images so that would limit it's usefulness. However I think that covers what you asked for.

**Comment by skittlz444** [comment]
Actual for i2i ControlNet, if you leave the CN image field blank, it will use the image supplied in the i2i image input field. While I don't think you can supply that via the extension, it works really well for bulk i2i which is my use case.

However with the ever growing list of useful extensions, and it looks like I'm not the first one requesting this feature, why not implement it properly like I said?

**Comment by Kryptortio** [comment]
Not sure what you mean by properly, doing a separate feature just for this would not change much compared to using script extensions maybe just a slight change in how you type the list. I don't think it would become much easier to use if you still want to be able to keep the same freedom as in the above example. Also it would still be an advanced feature only for people who have a grasp of how HTML works.

If I where to do something more in regards to this I'd be more inclined to just document this way of doing it under script extensions or for Controlnet specifically there is a [Show and tell](https://github.com/Kryptortio/SDAtom-WebUi-us/discussions/categories/show-and-tell) where such an example could be shared.
