### ISSUE TITLE
Broken with new Automatic1111 update

### ISSUE THREAD

**Issue by vxarg** [Kryptortio/SDAtom-WebUi-us#37]
The newest Automatic1111 update seems to have broken this extension.

It hasn't stopped worked completely, but the log now shows multiple errors in red whenever you open the page:
```
18:56:34: Failed to find the t2i object restoreFace
18:56:35: Failed to find the t2i object tiling
18:56:35: Failed to find the t2i object highresFix
18:56:35: Failed to find the t2i object scriptPromptMatrixPutVar
18:56:35: Failed to find the t2i object scriptPromptMatrixUseDiff
18:56:35: Failed to find the gradio element t2i object scriptXYZXtype
18:56:35: Failed to find the t2i object scriptXYZXVals
18:56:35: Failed to find the gradio element t2i object scriptXYZYtype
18:56:35: Failed to find the t2i object scriptXYZYVals
18:56:35: Failed to find the gradio element t2i object scriptXYZZtype
18:56:35: Failed to find the t2i object scriptXYZZVals
18:56:35: Failed to find the t2i object scriptXYZDrawLeg
18:56:35: Failed to find the t2i object scriptXYZIncludeSubImg
18:56:35: Failed to find the t2i object scriptXYZIncludeSubGrid
18:56:35: Failed to find the t2i object scriptXYZKeepMOne
18:56:35: Failed to find the t2i object scriptXYZGridMargin
18:56:35: Failed to find the secondary t2i object scriptXYZGridMargin
18:56:35: Failed to find the i2i object restoreFace
18:56:35: Failed to find the i2i object tiling
```

Clicking **add to queue** also shows more errrors (I won't be pasting everything here since it's too long).
Same for **process queue**.

Besides these errors, the extension is somewhat functional, but it's a bit hit or miss which functions work vs. which ones don't.
**Hi-Res Fix**, for example, doesn't work properly - the on or off state doesn't get saved or recalled, it only works if I turn it on before clicking **process queue**.

I suspect the new "accordion" for Hi-Res Fix instead of the On/Off toggle might be what's causing this.

**Comment by Kryptortio** [comment]
Thanks, hopefully these issues should now be solved. However to get all of them working you have to [manually change some settings](https://github.com/Kryptortio/SDAtom-WebUi-us#known-issues). Closing this for now but let me know if I missed something.
