### ISSUE TITLE
The extension causes automatic1111 infinite loading loop to - extensions, lora, textual inversion and checkpoint tabs

### ISSUE THREAD

**Issue by doremmy** [Kryptortio/SDAtom-WebUi-us#38]
The tabs won't load unless the "refresh" button is pressed and after that the infinite loading loop makes it so the content of the tabs are under a grey overlay which makes it hard to see the items.

The moment I deleted the extension the infinite loading loop disappeared.

 •  python: 3.10.11  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2  
This were my versions but it happened on older versions also.
I'm not a programmer I don't know what else to say.

Thank you, have a great day!

**Comment by Kryptortio** [comment]
Might be other extensions you are using that interfere with this one. Try with only this one or look at the  [Troubleshooting](https://github.com/Kryptortio/SDAtom-WebUi-us#troubleshooting) section to get more information (like console output).
