### ISSUE TITLE
Add to queue button disapeared

### ISSUE THREAD

**Issue by xmattar** [Kryptortio/SDAtom-WebUi-us#39]
the add to queue button disappeared randomly and it took some of my newest prompts i created and added to queue

this is one of the best tools i have ever used and really want it back, i tried updating and applying a restart, i searched for new versions
![image_2023-12-10_174815629](https://github.com/Kryptortio/SDAtom-WebUi-us/assets/70268334/7dccd315-17e0-4608-bd6b-321a27fb19c6)

**Comment by Kryptortio** [comment]
There is a [troubleshooting](https://github.com/Kryptortio/SDAtom-WebUi-us#troubleshooting) section you can check out but it works for me (v1.6.1) so it's likely one of your other extensions that is not compatible with mine, you could try disabling some to see if that fixes the issue.

**Comment by BurnZeZ** [comment]
This extension is incompatible: https://github.com/ThereforeGames/sd-webui-breadcrumbs

**Comment by BurnZeZ** [comment]
This extension is incompatible, at least: https://github.com/ThereforeGames/sd-webui-breadcrumbs

**Comment by Kryptortio** [comment]
> encountering this issue in 1.7.0, wondering if there'll be support for this for 1.7.0? thank you for your work!

I have 1.7.0 and am not experiencing this issue so try disabling some extensions to see if one of those are causing the issue.

However I pushed a new version with a small change that moves the extension above extensions like the one @BurnZeZ mentioned.
