### ISSUE TITLE
"Add to queue" button position and color, stack "move to top"

### ISSUE THREAD

**Issue by hansolocambo** [Kryptortio/SDAtom-WebUi-us#4]
I wanted to come here mainly to thank you so ! much for developing this script that is super efficient. I've been looking for a bulk rendering for days and this system of queue you've created exceeds my expectations. So damn useful (b^-^)b

1/ A small cosmetic "issue" in my opinion is the position of "Add to queue". I'm currently working on referencing the approximately 1900 artists used to train Stable Diffusion. And your scripts sure does help a freakin lot to bulk generate multi-prompts. I generate 40~60 images per artist, keep the 4 best and organize all that by periods in Art History (insane task...).
Doing that I have to click "add to queue" constantly and it's often more tempting to click on the ultra large and visible "Interrupt" than on the tiny and barely visible "Add to queue"  (black letters on dark grey background..)

Could you please consider looking for a better position for "add to queue", and changing the black letters on a dark grey background by white on orange, similar to Automatic1111's _Generate_ and _Skip_ buttons.

Some ideas about what "add to queue" could look like in the screenshot below, if you feel like it's not a bad idea to change that. 
![Add to Queue Automatic1111 ](https://user-images.githubusercontent.com/33687288/212571433-b5b79f21-af75-40e2-b778-a3b328760cda.png)

2/ I queue lots of prompts. But quiet often, while I organize the results, I realize that I need something to be generated right now. I can of course add the prompt, and click 50 times of the up arrow to move the prompt I need right now to the top. It's feasible which is already great really, but not convenient. 
Could you please consider, on top of the up and down arrows already there, adding another arrow that would move the queued prompt straight to the top of the list. So that it'll be processed next. That would be very useful.

Thanks again for sharing this truly great script. I hope you'll find my request worth some interest and that's it's eventually possible to code something like that. 

Cheers (b^-^)b

**Comment by Kryptortio** [comment]
1. I like having it like that for easy access without having to scroll so I will not be changing this. However I added [a feature where you can customize this yourself](https://github.com/Kryptortio/SDAtom-WebUi-us#script-extensions) instead. 
2. Added

**Comment by hansolocambo** [comment]
These move to top/bottom arrows are really useful. 
Thanks a lot [Kryptortio].
