### ISSUE TITLE
Keybpoard shortcuts 

### ISSUE THREAD

**Issue by vis223** [Kryptortio/SDAtom-WebUi-us#41]
Brilliant extension to A111.|
My only problem is the amount of scrolling involved between tweaking. adding. and processing. 
On my browser these settings are so far apart I get terrible RSI with all the scrolling.
Is there not a way I could add to the queue using key combinations instead of using the mouse?
For example, the way control enter generates in a111.
I guess maybe it's a limitation since it is not the same as most a111 extensions (I'm not too technical but saw this mentioned in here)Perhaps I can find a third-party app that will do this. A power toy even,.
Anyway, just a suggestion.. In all respects it's way better the generate forever

**Comment by Kryptortio** [comment]
Not sure why you need to scroll when the add to queue button is supposed to always be in to top corner.

However this is easily accomplished with an [extension snippet](https://github.com/Kryptortio/SDAtom-WebUi-us?tab=readme-ov-file#script-extensions) 

```
document.addEventListener('keydown', (event) => {
	if(event.ctrlKey && event.key == " ") {
		 conf.ui.addToQueueButton.click();
	}
});
```
CTRL+Enter is already taken but this one adds CTRL+Space
