### ISSUE TITLE
queue file location (for extension)

### ISSUE THREAD

**Issue by GGame666** [Kryptortio/SDAtom-WebUi-us#44]
I realize that this might be a dumb question but I would like to know where the extension (not the script) saves its file of at least its name

**Comment by Kryptortio** [comment]
File? The script data is stored in [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) the script is stored the same as other extensions \stable-diffusion-webui\extensions\SDAtom-WebUi-client-queue-ext\javascript
