### ISSUE TITLE
Gradio 4.0 Support, Specifically Latest Forge.

### ISSUE THREAD

**Issue by kyle215ps3** [Kryptortio/SDAtom-WebUi-us#46]
I still use this amazing extension and it has not failed me.

I do hope that this will be supported for Gradio 4.0 since it does not work on the newest version of Forge, and I believe A1111 since they updated to gradio 4 as well. And would like to try some of the new stuff on there, but still have this with me as well.

I believe it's Gradio 4 that might be causing this to not work anymore.

**Comment by Kryptortio** [comment]
Sorry, I've never used Forge, this extension was built for AUTOMATIC1111. I updated to the latest version of AUTOMATIC1111 and it seems to still be working. I did add a license though in case anyone would like to fork it to support different applications.

**Comment by kyle215ps3** [comment]
> Sorry, I've never used Forge, this extension was built for AUTOMATIC1111. I updated to the latest version of AUTOMATIC1111 and it seems to still be working. I did add a license though in case anyone would like to fork it to support different applications.

Ok :) No worries at all :D Thank you again for the awesome extension!
