### ISSUE TITLE
Could this be made to work with the API? So you could batch over multiple machines?

### ISSUE THREAD

**Issue by terbo** [Kryptortio/SDAtom-WebUi-us#5]
I wonder how exactly the script interacts with the web page,
and if that could be adopted to use the API so you could send a job off while waiting.
I could see the remove image outputs as being difficult to inject into the page,
but maybe you could just transfer them and put them into the output directory.

Could this be a simple way to use multiple GPU's for generation?

**Comment by Kryptortio** [comment]
Out of scope for this script I'm afraid, calling the API might be possible but it's something completely different to what this script is doing (it uses the GUI directly). Also don't think AUTOMATIC1111 has multi GPU support with API either.

I suggest you check out other venues for mult GPU support 

https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/1621

https://github.com/rbbrdckybk/dream-factory
