### ISSUE TITLE
Latest A1111 update seems broke this extension

### ISSUE THREAD

**Issue by Ethan-Ming** [Kryptortio/SDAtom-WebUi-us#8]
Both Tampermonkey script and extension method not working anymore

**Comment by Kryptortio** [comment]
Working on it, they have updated [gradio](https://gradio.app/) I think so the GUI is working differently now. I will try to have an update fixing it later today. In the meantime if you have updated and need to use the queue you should be able to [go back](https://github.com/Kryptortio/SDAtom-WebUi-us#troubleshooting) temporarily to an [earlier version](https://github.com/Kryptortio/SDAtom-WebUi-us#limitations).

**Comment by Kryptortio** [comment]
I think it should be fixed now but there was some pretty big changes needed so there could be more issues, let me know if you find any.
