### ISSUE TITLE
[Feature Request] A way to change paramaters for all jobs

### ISSUE THREAD

**Issue by uwidev** [Kryptortio/SDAtom-WebUi-us#9]
First off, great job on the plugin. It makes running generation tests on various trained models so much easier.

**Feature**
Users should now be able to adjust specified parameters for all currently queued jobs.

This can be implemented as a simple regex search/replace applied to all jobs, but I think the more elegant solution would be to have a dropbox of all keys, with a text box of the desired value.

**Why?**
For some jobs, after running them, I might want to run them on a different specific seed. Or perhaps, while I was adding batches, I realized that a parameter wasn't set up correctly. I would have to create the batch completely from scratch again. With this change, it can save a lot of time.

edit - I just noticed there's a "Load" function, to load a saved job. I guess this could be used for now to modify a batch script without manually editing the string, which is what I've been doing, but can still be tedious when fixing multiple jobs at once.

**Comment by Kryptortio** [comment]
There is now a search and replace feature under script settings.
